In [1]:
# 부모 클래스 — 모든 캐릭터의 공통
class Character:
    def __init__(self, name):
        self.name = name
        self.hp = 100
    def info(self):
        print(f"{self.name} (HP {self.hp})")

# 자식 클래스 — Character를 물려받음
class Warrior(Character):
    def attack(self):
        print(f"{self.name}: 칼을 휘두른다!")

w = Warrior("아서")
w.info()      # 물려받은 메서드 → 아서 (HP 100)
w.attack()    # 자기만의 메서드 → 아서: 칼을 휘두른다!

아서 (HP 100)
아서: 칼을 휘두른다!

# Super
</br> 부모의 기능 물려받기 
</br>
</br> *오버라이딩시 부모의 기능도 불러오기.  
</br> *자식 생성자에서는 초기화가 안되기에 부모 생성자를 불러와서 초기화할떄 __init__ super().__init__()

In [2]:
class Character:
    def __init__(self, name):
        self.name = name
        self.hp = 100

class Mage(Character):
    def __init__(self, name):
        super().__init__(name)   # 부모의 초기화 먼저 (name, hp 설정)
        self.mp = 50              # 마법사만의 속성 추가

m = Mage("간달프")
print(m.name, m.hp, m.mp)   # 간달프 100 50

간달프 100 50

# Over Riding 
</br> 부모 한테 물려 받은것을 덮어 쓰기

In [4]:
class Character:
    def attack(self):
        print("기본 공격!")

class Warrior(Character):
    def attack(self):          # 같은 이름 → 덮어씀
        super().attack()
        print("강력한 검격! (3배 데미지)")

Character().attack()   # 기본 공격!
Warrior().attack()     # 강력한 검격! (자식 것이 우선)

기본 공격!
기본 공격!
강력한 검격! (3배 데미지)

In [ ]:
# 부모 클래스 — 모든 캐릭터의 공통
class Character:
    def __init__(self, name):
        self.name = name
        self.hp = 100

    def info(self):
        print(f"{self.name} (HP {self.hp})")

# 자식 클래스 — Character를 물려받음
class Warrior(Character):
    def attack(self):
        print(f"{self.name}: 칼을 휘두른다!")

class Animal:

c = Character('기본')
c.info()
c.attack()
w = Warrior("아서")
w.info()      # 물려받은 메서드 → 아서 (HP 100)
w.attack()    # 자기만의 메서드 → 아서: 칼을 휘두른다!

# 매직 매서드
</br>
__~~__ 형태를 매직메서드( 던더 메서드 ) 라고 한다. 특정 상황에서는 자동으로 호출된다.

In [5]:
class Dog:
    def __init__(self, name):
        self.name = name

d = Dog("바둑이")
print(d)    #  ← 알아보기 힘듦

class Dog2:
    def __init__(self, name):
        self.name = name
    def __str__(self):        # print할 때 자동 호출
        return f"강아지 {self.name}"

d2 = Dog2("뽀삐")
print(d2)   # 강아지 뽀삐 ← 읽기 좋다!

<__main__.Dog object at 0x0000023BD2D3D6A0>
강아지 뽀삐

# 캡슐화
</br>

In [11]:
class Account:
    def __init__(self, balance):
        self._balance = balance

    def deposit(self, amount):
        if amount > 0:
            self._balance += amount

    def withdraw(self, amount):
        if amount <= self._balance:
            self._balance -= amount
            print(f"{amount}원 출금 완료")
        else:
            print(f"잔액이 부족합니다. (현재 잔고: {self._balance}원 / 요청 금액: {amount}원)")
            

    def get_balance(self):
        return self._balance

acc = Account(1000)
acc.deposit(500)
acc.withdraw(200)
print(acc.get_balance())
acc.withdraw(2000)
print(acc.get_balance())

200원 출금 완료
1300
잔액이 부족합니다. (현재 잔고: 1300원 / 요청 금액: 2000원)
1300

# raise
</br>
프로그램 실행 중에 우리가 원하는 타이밍에 강제로 에러(Exception)를 터뜨리는 역할
</br>raise 에러이름("메시지") 형태로 사용
```try:
    print("출금을 시도합니다.")
    raise ValueError("잔고가 부족합니다.") # 1. 여기서 에러를 휙 던짐!
    print("이 줄은 실행되지 않습니다.")     # 에러가 발생하면 다음 코드는 건너뜁니다.

except ValueError as e:                 # 2. 던진 에러를 여기서 착 잡음!
    print(f"에러 발생 수습 중: {e}")        # 3. "에러 발생 수습 중: 잔고가 부족합니다." 출력
```

In [ ]:
def withdraw(self, amount):
    try:
        if amount > self._balance:
            # 강제로 에러를 발생시켜 except로 던집니다.
            raise ValueError("잔고가 부족합니다.")
        
        self._balance -= amount
        print(f"{amount}원 출금 완료")
        
    except ValueError as e:
        # raise된 에러를 여기서 잡아서 처리합니다.
        print(f"[경고] {self._balance}원이 부족합니다. ({e})")
        
    finally:
        # 에러가 나든 안 나든 무조건 실행됩니다.
        print("why come here")

In [15]:
class Shape:
    def __init__(self, name):
        self.name = name
    def area(self):
        return 0
    def __str__(self):
        return f"{self.name}의 넓이: {self.area()}"

class Rectangle(Shape):
    def __init__(self, w, h):
        super().__init__("직사각형")
        self.w = w
        self.h = h
    def area(self):          # 오버라이딩
        return self.w * self.h

class Circle(Shape):
    def __init__(self, r):
        super().__init__("원")
        self.r = r
    def area(self):
        return 3.14 * self.r ** 2

class Triangle(Shape):
    def __init__(self,w,h):
        super().__init__('삼각형')
        self.w = w
        self.h = h
    def area(self):
        return int(self.w * self.h /2)

# __str__ 덕분에 print가 깔끔
print(Rectangle(4, 5))   # 직사각형의 넓이: 20
print(Circle(3))        # 원의 넓이: 28.26
print(Triangle(3,4))

직사각형의 넓이: 20
원의 넓이: 28.26
삼각형의 넓이: 6

In [ ]:
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        return "..."

    def __str__(self):
        return f'동물 {self.name}'          # "동물 흰둥이"


class Dog(Animal):
    def speak(self):
        return '멍멍'


class Cat(Animal):
    def speak(self):
        return '야옹'


class Puppy(Dog):
    def __init__(self, name, age):
        super().__init__(name)                 # 부모의 준비를 먼저
        self.age = age

    def speak(self):
        return f'{super().speak()}!'          # 부모의 소리 뒤에 "!"

def chorus(animals):
    """동물들의 소리를 공백으로 이어 붙인다."""
    return " ".join(a.speak() for a in animals)

# Pandas
</br> 데이터 테이블 전처리 라이브러리

In [ ]:
import pandas as pd

s1 = pd.Series([5000, 30000, 20000, 15000])
display(s1)

s2 = pd.Series({
    '2020-03-03' : 5000, "2020-03-04": 30000,
    '2020-03-05' : 20000, "2020-03-06": 15000})

display(s2)

0     5000
1    30000
2    20000
3    15000
dtype: int64

2020-03-03     5000
2020-03-04    30000
2020-03-05    20000
2020-03-06    15000
dtype: int64

In [46]:
import pandas as pd
# pd.Series : Index 와 값을 같이 입력
s3 = pd.Series([5000,30000,20000,15000],\
    index = ['2020-03-03','2020-03-04','2020-03-05','2020-03-06'],\
    name ='durian')
s3.index.name = 'dates'
s3

dates
2020-03-03     5000
2020-03-04    30000
2020-03-05    20000
2020-03-06    15000
Name: durian, dtype: int64

In [44]:
df = pd.DataFrame({\
    "2020-03-03":[4000, 20000, 10000],\
    "2020-03-04":[5000, 8000, 11000],\
    "2020-03-05":[6000, 9000, 12000]},\
    index = ["apple",'banana','cherry'])
display(df)

df['2020-03-03']
# df.loc['banana','2020-03-03']
df.loc['banana']

        2020-03-03  2020-03-04  2020-03-05
apple         4000        5000        6000
banana       20000        8000        9000
cherry       10000       11000       12000

2020-03-03    20000
2020-03-04     8000
2020-03-05     9000
Name: banana, dtype: int64

In [38]:
df1 = pd.DataFrame([
    [4000, 20000, 10000],\
    [5000, 8000, 11000],\
    [6000, 9000, 12000]])
df1.index = [['apple','banana','cherry']]
df1.columns = [['03.03','03.04','03.05']]

df1

       03.03  03.04  03.05
apple   4000  20000  10000
banana  5000   8000  11000
cherry  6000   9000  12000

In [34]:
s1 = pd.Series([4000, 20000, 10000],\
    index=['03.03','03.04','03.05'],\
    name='apple')
s2 = pd.Series([5000, 8000, 11000],\
    index=['03.03','03.04','03.05'],\
    name='apple')
s3 = pd.Series([6000, 9000, 12000],\
    index=['03.03','03.04','03.05'],\
    name='cherry')
df = pd.DataFrame([s1,s2,s3])
df

        03.03  03.04  03.05
apple    4000  20000  10000
apple    5000   8000  11000
cherry   6000   9000  12000

In [49]:
df = pd.DataFrame({

    "2020-03-03":[4000, 20000, 10000],
    "2020-03-04":[5000, 8000, 11000],
    "2020-03-05":[6000, 9000, 12000]},
    index = ['apple','banana','cherry'])
display(df)

df['2020-03-03']
df.loc['banana']
df.loc[df['2020-03-03'] > 4000, :]

        2020-03-03  2020-03-04  2020-03-05
apple         4000        5000        6000
banana       20000        8000        9000
cherry       10000       11000       12000

        2020-03-03  2020-03-04  2020-03-05
banana       20000        8000        9000
cherry       10000       11000       12000

In [ ]:
import pandas as pd
import numpy as np
"""
lines = [
    '1997,Ford,E350,"ac,abs,moon", 3000.00',
]
with open("./dataset-no-column.csv",'w',encoding='utf-8') as f"
"""
data = pd.read_csv("./dataset-no-column.csv")
display(data)
data = pd.read_csv("./dataset-no-column.csv",header=None)
display(data)
df=pd.DataFrame(np.random.randn(10,4), columns=['A','B','C','D'])
display(df)
df.to_csv("./result.csv")

,1997,Ford,E350,"ac, abs, moon",3000.00
0,1999,Chevy,"Venture ""Extended Edition""",NaN,4900.0
1,1999,Chevy,"Venture ""Extended Edition, Very Large""",NaN,5000.0
2,1996,Jeep,Grand Cherokee,"MUST SELL! air, moon roof, loaded",4799.0

,0,1,2,3,4
0,1997,Ford,E350,"ac, abs, moon",3000.0
1,1999,Chevy,"Venture ""Extended Edition""",NaN,4900.0
2,1999,Chevy,"Venture ""Extended Edition, Very Large""",NaN,5000.0
3,1996,Jeep,Grand Cherokee,"MUST SELL! air, moon roof, loaded",4799.0

          A         B         C         D
0 -0.598689  0.986253  0.775178  0.269046
1  1.102343 -0.605472  0.896162  1.104640
2 -0.832289  1.652367 -0.766344  0.112518
3  0.439109  1.346340 -1.780711  1.051416
4 -0.381859  1.146463  1.049772  1.138799
5 -1.198921  1.060927  0.368025  0.533053
6 -0.349113 -0.779679 -0.422656  1.316970
7 -0.445897 -0.067340  0.914190  0.654480
8 -0.161645 -0.279344 -0.347185  0.164041
9  1.370226  0.184651  0.199443 -0.359738

In [ ]:
import numpy as np

dates = pd.date_range('20130101', periods = 6)
df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns= list('ABCD'))
display(df)

df1 = df.reindex(index = dates[0:4], columns = list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
display(df1)

display(pd.isna(df1))                   # 어떤것이 NaN 인지?
display(df1.dropna(how='any'))          # 결측치 버림 (dropna() =  dropna(axis = 0, how = "any"))
display(df1.fillna(value=5))            # 결측치 채우기

                   A         B         C         D
2013-01-01 -2.288239 -1.969646  0.210544  0.172580
2013-01-02 -0.114567  0.564699 -0.451878 -1.299172
2013-01-03  0.857821  1.985092 -0.747761  0.993587
2013-01-04  0.107634 -1.580016  1.586839  1.609946
2013-01-05  0.014871 -0.166216 -1.008292 -1.910256
2013-01-06  0.701016 -0.972091 -0.828886  1.699553

                   A         B         C         D    E
2013-01-01 -2.288239 -1.969646  0.210544  0.172580  1.0
2013-01-02 -0.114567  0.564699 -0.451878 -1.299172  1.0
2013-01-03  0.857821  1.985092 -0.747761  0.993587  NaN
2013-01-04  0.107634 -1.580016  1.586839  1.609946  NaN

                A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True

                   A         B         C         D    E
2013-01-01 -2.288239 -1.969646  0.210544  0.172580  1.0
2013-01-02 -0.114567  0.564699 -0.451878 -1.299172  1.0

                   A         B         C         D    E
2013-01-01 -2.288239 -1.969646  0.210544  0.172580  1.0
2013-01-02 -0.114567  0.564699 -0.451878 -1.299172  1.0
2013-01-03  0.857821  1.985092 -0.747761  0.993587  5.0
2013-01-04  0.107634 -1.580016  1.586839  1.609946  5.0

In [59]:
df = pd.DataFrame(
    {'Favorite Food': ['Alfredo Pasta', "Bobba",'Croissants', "danish Rolls", 'Edamame', 'Fish',"Ice Cream"]},
    index = pd.Index(['Alfred', 'Bob', 'Cris', 'Daniel', 'Edward', 'Fitx', 'Ivan'], name = 'Name'))
df2 = pd.DataFrame(
    {'favorite Country':['Albania', 'Croatia', 'Denmark', 'Fiji', 'Germany', 'Haiti']},
    index = pd.Index(['Alfred', 'Cris', 'Daniel', 'Edward', 'Fitx', 'Ivan'], name = 'Name'))
display(df1)
display(df2)

display(pd.concat([df1, df2], sort = False))
display(pd.concat([df1, df2], axis = 1, sort = True))

                   A         B         C         D    E
2013-01-01 -2.288239 -1.969646  0.210544  0.172580  1.0
2013-01-02 -0.114567  0.564699 -0.451878 -1.299172  1.0
2013-01-03  0.857821  1.985092 -0.747761  0.993587  NaN
2013-01-04  0.107634 -1.580016  1.586839  1.609946  NaN

       favorite Country
Name
Alfred          Albania
Cris            Croatia
Daniel          Denmark
Edward             Fiji
Fitx            Germany
Ivan              Haiti

,A,B,C,D,E,favorite Country
2013-01-01 00:00:00,-2.288239,-1.969646,0.210544,0.172580,1.0,NaN
2013-01-02 00:00:00,-0.114567,0.564699,-0.451878,-1.299172,1.0,NaN
2013-01-03 00:00:00,0.857821,1.985092,-0.747761,0.993587,NaN,NaN
2013-01-04 00:00:00,0.107634,-1.580016,1.586839,1.609946,NaN,NaN
Alfred,NaN,NaN,NaN,NaN,NaN,Albania
Cris,NaN,NaN,NaN,NaN,NaN,Croatia
Daniel,NaN,NaN,NaN,NaN,NaN,Denmark
Edward,NaN,NaN,NaN,NaN,NaN,Fiji
Fitx,NaN,NaN,NaN,NaN,NaN,Germany
Ivan,NaN,NaN,NaN,NaN,NaN,Haiti

,A,B,C,D,E,favorite Country
2013-01-01 00:00:00,-2.288239,-1.969646,0.210544,0.172580,1.0,NaN
2013-01-02 00:00:00,-0.114567,0.564699,-0.451878,-1.299172,1.0,NaN
2013-01-03 00:00:00,0.857821,1.985092,-0.747761,0.993587,NaN,NaN
2013-01-04 00:00:00,0.107634,-1.580016,1.586839,1.609946,NaN,NaN
Alfred,NaN,NaN,NaN,NaN,NaN,Albania
Cris,NaN,NaN,NaN,NaN,NaN,Croatia
Daniel,NaN,NaN,NaN,NaN,NaN,Denmark
Edward,NaN,NaN,NaN,NaN,NaN,Fiji
Fitx,NaN,NaN,NaN,NaN,NaN,Germany
Ivan,NaN,NaN,NaN,NaN,NaN,Haiti

In [ ]:
from dataclasses import dataclass

@dataclass
class InventoryItem:
    name: str
    unit_price:float
    quantity_on_hand: int = 0
    
    @staticmethod
    def func1():
        print('hi')

a = InventoryItem(name = 'a', unit_price = 1.2, quantity_on_hand =1)
# a = InventoryItem(name = '1', unit_price = 1.2, quantity_on_hand =1)
b = InventoryItem(name = 'b', unit_price = 1.2, quantity_on_hand =1)

print(a is b)
print(a = b)

In [70]:
class Human:
    population = 0

    # 사실 __new__가 가장 처음 되는것 __init__보다 우선 순위다.
    def __new__(cls, *args):
        print('cls :', cls)
        print('new :', args)
        return super().__new__(cls)
    
    def __init__(self, name):
        self.name = name
        self.age = 0
        print(f'야호 나는 {self.name}이다.')
        Human.population += 1

    def __add__(self,target):
        return self.name + target.name

    def __ge__(self,target):
        return self.age >= target.age

a = Human('철수')
b = Human('영희')
print(Human.population)
# print(a+b)
# a >= b

cls : <class '__main__.Human'>
new : ('철수',)
야호 나는 철수이다.
cls : <class '__main__.Human'>
new : ('영희',)
야호 나는 영희이다.
2

In [71]:
class User:
    def __init__(self,email, pwd):
        self.email = email
        self.pwd = pwd
        print(self.email, self.pwd)

    @classmethod
    def fromDict(cls, d):
        return cls(d['email'],d['password'])

In [72]:
d = {'email':'user@test.com', 'password':1234}
user = User.fromDict(d)

user@test.com 1234

In [ ]:
a,b = 1,2
print(b,a)
a,b = b,a
# 변수나 튜플을 마지막에 적으면 representation 이라해서 출력해주는 기능이 있다.
# __repr__(self)
b,a

2 1

(1, 2)

In [74]:
class C:
    def __init__(self):
        pass
    def __repr__(self):
        return "repr!!!"
    def __str__(self):
        return "print!!!"

c=C()
c

repr!!!

In [79]:
# inheritance
class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def hello(self):
        print(f"HI 나는 {self.name}이다. {self.age}살 이다.")

    def dance(self):
        print(f'{self.name}는 춤추기')

class NPC(Human):
    def __init__(self, name, age, mp):
        super().__init__(name, age)
        print('야호')
        self.mp = mp

    def hello(self):
        print(f'hi 나는 {self.name}이다. {self.age}살이다 나는 NPC이다')

    def cast(self):
        print(f'{self.name}은 화염구를 영창했다. 마나가 20줄었다 현재 마나는 {self.mp-20}')

h1 = Human('개똥', 30)
h1.hello()
h2 = NPC('소똥', 40, 30)
h2.hello()
h2.dance()
h2.cast()

HI 나는 개똥이다. 30살 이다.
야호
hi 나는 소똥이다. 40살이다 나는 NPC이다
소똥는 춤추기
소똥은 화염구를 영창했다. 마나가 20줄었다 현재 마나는 10

In [ ]:
class Adder:
    def __init__(self,v):
        self.__v = v

    # getter: 속성을 읽을 때 호출됩니다.
    @property
    def v(self):
        return self.__v

    # setter : 속성에 값을 대입할 때(=) 호출됩니다.
    @v.setter
    def v(self, value):
        if value < 0:
            raise ValueError('Value는 음수가 될 수 없습니다.')
        self.__v = value

    def __add__(self,target):
        if isinstance(target, Adder):
            return self.v + target.v
        else: return self.v + target

    def __radd__(self,target):
        return self.__add__(target)  
    
    def hello(self):
        print(self.__v)

a = Adder(1)
b = Adder(2)
c = Adder(3)
print(type(a+b))
print(a+b)

<class 'int'>
3

__add__
</br>a + 3 (왼쪽이 self)
</br>
</br>__radd__
</br>3+ a (오른쪽이 self)

In [88]:
class A:
    def __init__(self, value):
        self.value = value

    def __add__(self, other):
        return self.value + other
    
    def __radd__(self, other):
        return self.__add__(other)
    


a = A(1)
b = A(2)
c = A(3)
d = a + b + c
print(d)

6

In [91]:
# composition

class Player:
    def __init__(self,name,hp,armor,weapon):
        self.name = name
        self.hp = hp
        self.armor = armor
        self.weapon = weapon
        self.sruvieve = True

    def attacked(self,dmg):
        dmg = dmg - self.armor.armor
        if dmg < 0:
            dmg = 0
        self.hp -= dmg

        if self.hp <= 0:
            print('사망')
            self.survive = False
        else:
            print(f'아야.... 남은피:{self.hp}')

    def attack(self,target):
        dmg = self.weapon.dmg
        print(f'{self.name} =공격->{taget.name}')
        target.attacked(dmg)
        return None

class Armor:
    def __init__(self, name, armor):
        self.name = name
        self.armor = armor

class Weapon:
    def __init__(self, name, dmg):
        self.name = name
        self.dmg = dmg

armor1 = Armor('누더기',1)
weapon1 = Weapon('나뭇가지',20)
player = Player('개똥이', 100, armor1, weapon1)
player = Player('소똥이', 100, armor1, weapon1)